#!/bin/bash

SCRIPT_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

if [ ! -f /.dockerenv ]; then  

   if [ -z "$DOCKER_IMAGE_NAME" ]; then
      echo "Missing DOCKER_IMAGE_NAME environment variable"
      exit 1
   fi

   if [ -z "$DOCKER_IMAGE" ]; then
      echo "Missing DOCKER_IMAGE environment variable"
      exit 2
   fi

   DOCKER_HOSTNAME=`hostname`[$DOCKER_IMAGE_NAME]

   if [ "$#" -eq 0 ]; then
      INTERACTIVE_DOCKER_SHELL=-it
   fi

   docker run --hostname $DOCKER_HOSTNAME \
      -v $SCRIPT_PATH:$SCRIPT_PATH $DOCKER_MOUNT_VOLS -v $PWD:$PWD \
      -e "TERM=xterm-256color" $INTERACTIVE_DOCKER_SHELL \
      $DOCKER_IMAGE $SCRIPT_PATH/dc-bash \
      $USER $UID $PWD $@ 

else
   if [ $UID -ne 0 ]; then
      $@ 
      exit $?  
   fi
   USER=$1
   UID_P=$2
   INIT_PATH=$3
   shift 3

   echo "Add $USER (uid=$UID_P)"
   useradd -u $UID_P $USER
   su $USER -c id

   if [ ! -d /home/$USER ]; then
      echo "Creating /home/$USER"
      mkdir /home/$USER
   fi

   chown $UID_P:$UID_P /home/$USER

   cp /root/.bashrc /home/$USER/
   cd $INIT_PATH

   echo_buildenv()
   {
      echo export PATH=$PATH
      echo cd $INIT_PATH
   }

   if [ "$#" -ne 0 ]; then
      echo_buildenv > $INIT_PATH/.run.tmp.sh
      echo $@ >> $INIT_PATH/.run.tmp.sh
      chmod a+x $INIT_PATH/.run.tmp.sh
      su $USER -c $INIT_PATH/.run.tmp.sh
      rm $INIT_PATH/.run.tmp.sh
   else
      echo_buildenv >> /home/$USER/.bashrc
      su $USER
   fi

fi
