#!/bin/bash

SCRIPT_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

if [ ! -f /.dockerenv ]; then  

   if [ -z "$DOCKER_IMAGE_NAME" ]; then
      echo "Missing DOCKER_IMAGE_NAME environment variable"
      exit 1
   fi

   if [ -z "$DOCKER_IMAGE" ]; then
      echo "Missing DOCKER_IMAGE environment variable"
      exit 2
   fi

   DOCKER_HOSTNAME=`hostname`[$DOCKER_IMAGE_NAME]

   if [ "$#" -eq 0 ]; then
      INTERACTIVE_DOCKER_SHELL=-it
   fi

   docker run --hostname $DOCKER_HOSTNAME \
      -v $SCRIPT_PATH:$SCRIPT_PATH $DOCKER_MOUNT_VOLS -v $PWD:$PWD \
      -e "TERM=xterm-256color" \
      -e "HOST_USER=$USER" \
      -e "HOST_UID=$UID" \
      -e "HOST_PWD=$PWD" \
      $INTERACTIVE_DOCKER_SHELL \
      --entrypoint /bin/bash \
      $DOCKER_IMAGE $SCRIPT_PATH/dc-bash \
      $@ 

else
   if [ $UID -ne 0 ]; then
      $@ 
      exit $?  
   fi

   echo "Add $HOST_USER (uid=$HOST_UID)"
   useradd -u $HOST_UID $HOST_USER
   su $HOST_USER -c id

   if [ ! -d /home/$HOST_USER ]; then
      echo "Creating /home/$HOST_USER"
      mkdir /home/$HOST_USER
   fi

   chown $HOST_UID:$HOST_UID /home/$HOST_USER

   cp /root/.bashrc /home/$HOST_USER/
   cd $HOST_PWD

   echo_buildenv()
   {
      echo export PATH=$PATH
      if [ ! -z "$ANDROID_NDK" ]; then
        echo export ANDROID_NDK=$ANDROID_NDK
      fi
      if [ ! -z "$ANDROID_NDK_HOME" ]; then
	echo export ANDROID_NDK_HOME=$ANDROID_NDK_HOME
      fi
      if [ ! -z "$ANDROID_HOME" ]; then
	echo export ANDROID_HOME=$ANDROID_HOME
      fi
      echo cd $HOST_PWD
   }

   if [ "$#" -ne 0 ]; then
      echo_buildenv > $HOST_PWD/.run.tmp.sh
      echo $@ >> $HOST_PWD/.run.tmp.sh
      chmod a+x $HOST_PWD/.run.tmp.sh
      su $HOST_USER -c $HOST_PWD/.run.tmp.sh
      rm $HOST_PWD/.run.tmp.sh
   else
      echo_buildenv >> /home/$HOST_USER/.bashrc
      su $HOST_USER
   fi
fi
